create database barbershop_db;

create user 'USBARBER'@'localhost' identified BY 'Us*B4rb3rM4';
GRANT ALL PRIVILEGES ON barbershop_db.* TO 'USBARBER'@'localhost';

use barbershop_db;

CREATE TABLE IMAGE (
	ID_IMAGE INT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(150),
    TYPE VARCHAR(50) NOT NULL,
    PATH LONGBLOB,
    EXTERNAL_PATH VARCHAR(1000),
    STATUS VARCHAR(15),
    CREATE_USER INT,
    CREATE_DATE DATETIME,
    MODIFY_USER INT,
    MODIFY_DATE DATETIME,
    PRIMARY KEY(ID_IMAGE)
);

CREATE TABLE CUSTOMER (
	ID_CUSTOMER INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100),
    ALIAS_NAME VARCHAR(50),
    PHONE_NUMBER VARCHAR(15),
    MAIL VARCHAR(150),
    IMG_PERFIL INT,
    IMG_QR INT,
    ID_QR VARCHAR(12) UNIQUE,
    ACCESS_CODE VARCHAR(100) NOT NULL,
    STATUS VARCHAR(15),
    CREATE_USER INT,
    CREATE_DATE DATETIME,
    MODIFY_USER INT,
    MODIFY_DATE DATETIME,
    PRIMARY KEY (ID_CUSTOMER),
    FOREIGN KEY (IMG_PERFIL) REFERENCES IMAGE(ID_IMAGE),
    FOREIGN KEY (IMG_QR) REFERENCES IMAGE(ID_IMAGE)
);

CREATE TABLE EMPLOYEE (
	ID_EMPLOYEE INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(150),
    LAST_NAME VARCHAR(150),
    ROLE VARCHAR(10),
    PHONE_NUMBER VARCHAR(15),
    MAIL VARCHAR(150),
    IMG_PERFIL INT,
    STATUS VARCHAR(15),
    CREATE_USER INT,
    CREATE_DATE DATETIME,
    MODIFY_USER INT,
    MODIFY_DATE DATETIME,
    PRIMARY KEY (ID_EMPLOYEE)
);

CREATE TABLE ACCESS (
	ID_ACCESS INT NOT NULL AUTO_INCREMENT,
    ID_EMPLOYEE INT NOT NULL,
    ACCESS_CODE VARCHAR(100) NOT NULL,
    TOKEN VARCHAR(12),
    STATUS VARCHAR(15),
    CREATE_USER INT,
    CREATE_DATE DATETIME,
    MODIFY_USER INT,
    MODIFY_DATE DATETIME,
    PRIMARY KEY (ID_ACCESS),
    FOREIGN KEY (ID_EMPLOYEE) REFERENCES EMPLOYEE(ID_EMPLOYEE)
);

CREATE TABLE BUSINESS (
	ID_BUSINESS INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(150),
    LAST_NAME VARCHAR(150),
    IMG_LOGO INT,
    OWNER INT,
    STATUS VARCHAR(15),
    CREATE_USER INT,
    CREATE_DATE DATETIME,
    MODIFY_USER INT,
    MODIFY_DATE DATETIME,
    PRIMARY KEY (ID_BUSINESS),
    FOREIGN KEY (IMG_LOGO) REFERENCES IMAGE(ID_IMAGE),
    FOREIGN KEY (OWNER) REFERENCES EMPLOYEE(ID_EMPLOYEE)
);

/*AGREGAR TABLA SOLO PARA HORARIOS POR SUBSIDIARIA, FECHAS Y HORARIO INICIO, HORARIO FIN*/
CREATE TABLE SUBSIDIARY (
	ID_SUBSIDIARY INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(150),
    LOCATION VARCHAR(250),
    PHONE_NUMBER_1 VARCHAR(15),
    PHONE_NUMBER_2 VARCHAR(15),
    PHONE_NUMBER_3 VARCHAR(15),
    ID_BUSINESS INT NOT NULL,
    STATUS VARCHAR(15),
    CREATE_USER INT,
    CREATE_DATE DATETIME,
    MODIFY_USER INT,
    MODIFY_DATE DATETIME,
    PRIMARY KEY (ID_SUBSIDIARY),
    FOREIGN KEY (ID_BUSINESS) REFERENCES BUSINESS(ID_BUSINESS)
);

CREATE TABLE PRODUCT(
	ID_PRODUCT INT NOT NULL AUTO_INCREMENT,
    SKU VARCHAR(50) UNIQUE,
    NAME VARCHAR(150),
    DESCRIPTION VARCHAR(250),
    PRECIO DECIMAL,
    STOCK INT,
    VOLUME  DECIMAL,
    UNIT_MEASUREMENT VARCHAR(10), 
    TYPE VARCHAR(10),
    CATEGORY VARCHAR(10),
	STATUS VARCHAR(15),
    CREATE_USER INT,
    CREATE_DATE DATETIME,
    MODIFY_USER INT,
    MODIFY_DATE DATETIME,
    PRIMARY KEY (ID_PRODUCT)
);

CREATE TABLE PROMOTION (
	ID_PROMOTION INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(150),
    DESCRIPTION VARCHAR(500),
    CATEGORY VARCHAR(10),
    PERCENTAGE DECIMAL,
    VALIDITY_START DATETIME,
    VALIDITY_END DATETIME, 
    IMG_PUBLICITY INT,
    STATUS VARCHAR(15),
    CREATE_USER INT,
    CREATE_DATE DATETIME,
    MODIFY_USER INT,
    MODIFY_DATE DATETIME,
    PRIMARY KEY (ID_PROMOTION)
);

CREATE TABLE PROMOTION_PRODUCTS(
	ID_PROMOTION_PRODUCTS INT NOT NULL AUTO_INCREMENT,
    ID_PROMOTION INT NOT NULL,
    ID_PRODUCT INT NOT NULL,
    PRIMARY KEY(ID_PROMOTION_PRODUCTS),
    FOREIGN KEY(ID_PROMOTION) REFERENCES PROMOTION(ID_PROMOTION),
    FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT)
);

CREATE TABLE TRANSACTION (
	ID_TRANSACTION INT NOT NULL AUTO_INCREMENT,
    ID_OPERATION VARCHAR(20) UNIQUE,
    SUBTOTAL DECIMAL NOT NULL,
    TOTAL DECIMAL NOT NULL,
    TAX DECIMAL NOT NULL,
    PAYMENT_TYPE VARCHAR(10),
    TOTAL_DISCOUNT DECIMAL,
    REFERENCE VARCHAR(10),
    TRANSACTION_DATE DATETIME,
    ID_EMPLOYEE INT,
    STATUS VARCHAR(15),
    CREATE_USER INT,
    CREATE_DATE DATETIME,
    MODIFY_USER INT,
    MODIFY_DATE DATETIME,
    PRIMARY KEY (ID_TRANSACTION),
    FOREIGN KEY (ID_EMPLOYEE) REFERENCES EMPLOYEE(ID_EMPLOYEE)
);

CREATE TABLE TRANSACTION_PRODUCT (
	ID_TRANSACTION_PRODUCT INT NOT NULL AUTO_INCREMENT,
    ID_TRANSACTION INT,
    ID_PRODUCT INT,
    QUANTITY INT NOT NULL,
    UNIT_PRICE DECIMAL,
    SUBTOTAL DECIMAL,
    DISCOUNT_RATE DECIMAL,
    DISCOUNT_AMOUNT DECIMAL,
    AMOUNT DECIMAL,
    ID_PROMOTION INT,
    STATUS VARCHAR(15),
    CREATE_USER INT,
    CREATE_DATE DATETIME,
    MODIFY_USER INT,
    MODIFY_DATE DATETIME,
    PRIMARY KEY(ID_TRANSACTION_PRODUCT),
    FOREIGN KEY(ID_PROMOTION) REFERENCES PROMOTION(ID_PROMOTION)
);

CREATE TABLE SERVICE_TIME (
	ID_SERVICE_HOURS INT NOT NULL AUTO_INCREMENT,
    MINUTES_TIME INT,
    ID_PRODUCT INT,
    PRIMARY KEY (ID_SERVICE_HOURS),
    FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT)
);

CREATE TABLE RESERVATION (
	ID_RESERVATION INT NOT NULL AUTO_INCREMENT,
    DATE DATE,
    START_TIME TIME,
    END_TIME TIME,
    PRIMARY KEY (ID_RESERVATION)
);
/*Pendiente. 
	Crear tabla para reservaciones
    Validar como guardar el tiempo por servicio*/